name: Deploy plunit_assert Documentation

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SWI-Prolog
        run: |
          sudo apt-get update
          sudo apt-get install -y swi-prolog

      - name: Generate documentation
        run: |
          # swipl -g "load_files(plunit_assert), doc_save(., [format(html), doc_root(doc), title('PlUnit Assert Documentation')])" -t halt
          swipl -g "load_files(plunit_assert), doc_save(., [format(html), doc_root('./docs'), title('API Documentation for plunit_assert')])" -t halt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
